apiVersion: v1
kind: Pod
metadata:
  name: jenkins-docker-agent-pod
  labels:
    jenkins: slave
spec:
  containers:
  - name: docker
    image: docker:latest
    securityContext:
      privileged: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
      volumeMounts:
      - name: docker-socket
        mountPath: /var/run/docker.sock
  volumes:
  - hostPath:
      path: /var/run/docker.sock
    name: docker-socket
